blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://slack.vllm.ai
    about: Ask questions and discuss with other vLLM-Omni community members in our #sig-omni slack channel.
